name: 'Swift Setup'
branding:
  color: 'green'
  icon: 'play'
description: 'Setting Swift up.'
inputs:
  swift-installer:
    description: |
      The tool that installs Swift.
      "swiftenv" or "swiftly" is allowed for this value.
    required: false
    default: "swiftenv"
  swift-version:
    description: 'The version of Swift.'
    required: false
  swift-package-directory:
    description: 'The directory of your Swift package.'
    required: false
    default: '.'
runs:
  using: 'node24'
  main: './lib/main.js'
