#!/bin/bash

declare -r utils_directory=$(cd "$(dirname "$0")" && pwd)
declare -r repository_root=$(cd "${utils_directory}/.." && pwd)

declare -i nn=0

for line in $(python3 "${utils_directory}/prod-deps" 2>/dev/null); do
  if [ ! -d "${repository_root}/node_modules/${line}" ]; then
    echo "Error: ${line} is missing." >&2
    nn=$(( $nn + 1 ))
  fi
done

if [ $nn -eq 0 ]; then
  echo "All necessary modules for production are found."
fi

exit $(test $nn -eq 0)
