#!/bin/bash

declare -r repository_root="$(cd "$(cd "$(dirname "$0")" && pwd)/.." && pwd)"
declare -r package_directory="${repository_root}/swift-test-package"

set -x
swift test --package-path "$package_directory"
