#!/bin/bash

function extract_module_names() {
  local prev="--previous--module--name--"
  local filename="$1"
  cat "${filename}" | \
    grep -E '^[^A-Za-z]' | \
    sed -E 's/^[^@A-Za-z]+//g' | \
    sed -E 's/^[ ]*UNMET (OPTIONAL )?DEPENDENCY[ ]+//g' | \
    sed -E 's/@[0-9]+(\.[0-9]+)*([ ]+deduped)?.*$//g' | \
    sort | \
    while read line
  do
    if [ "${prev}" != "${line}" ]; then
      echo "${line}"
      prev="${line}"
    fi
  done
}

declare -r repository_root=$(cd "$(cd "$(dirname "$0")" && pwd)/.." && pwd)
declare -r temporary_directory="/tmp/Action-setup-swift/$(uuidgen)"
mkdir -p "${temporary_directory}"

declare -r prod_raw="${temporary_directory}/prod_raw.txt"
declare -r prod_shaped="${temporary_directory}/prod_shaped.txt"
declare -r dev_raw="${temporary_directory}/dev_raw.txt"
declare -r dev_shaped="${temporary_directory}/dev_shaped.txt"

cd "${repository_root}"
npm list -only prod >"${prod_raw}"
npm list -only dev >"${dev_raw}"
extract_module_names "${prod_raw}" >"${prod_shaped}"
extract_module_names "${dev_raw}" >"${dev_shaped}"

cat "${dev_shaped}" | while read line; do
  if ! cat "${prod_shaped}" | grep -q "${line}"; then
    echo "${line}"
  fi
done

