name: Test for branch
"on":
  push:
    branches:
      - "**"
    tags:
      - "!**"
jobs:
  branch-test:
    name: Test of Action-setup-swift with `swift-version` input.
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        swift-version:
          - 5.1.2
          - DEVELOPMENT-SNAPSHOT-2019-11-20-a
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Install Swift.
        uses: YOCKOW/Action-setup-swift@${{ github.ref }}
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: View Swift Version
        run: swift --version
      - name: Run Swift
        run: ./utils/swift-test
  branch-test-with-swift-version-file:
    name: Test of Action-setup-swift with ".swift-version" file.
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Install Swift.
        uses: YOCKOW/Action-setup-swift@${{ github.ref }}
        with:
          swift-package-directory: ./swift-test-package
      - name: View Swift Version
        run: swift --version
      - name: Run Swift
        run: ./utils/swift-test
