name: Check commits
"on":
  push:
    branches:
      - "**"
      - "!no-tests/**"
    tags:
      - "!**"
  pull_request:
    branches:
      - "**"
      - "!no-tests/**"
jobs:
  check-modules:
    name: Check Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-python@v1.1.1
        with:
          python-version: "3.7"
      - name: Check whether or not unnecessary modules are installed.
        run: ./utils/check-unnecessary-modules
      - name: Check whether or not necessary modules are up-to-date.
        run: |
          npm install --production
          if [ -n "$(git diff -- ./node_modules)" ]; then
            echo "Modules are not up-to-date."
            exit 1
          fi
  check-traspilation:
    name: Check whether or not transpilation is completed.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Check transpilation
        run: |+
          npm install
          npm run build
          if [ -n "$(git diff -- ./lib)" ]; then
            echo "Transpilation has not been completed."
            exit 1
          fi
