name: Check commits
"on":
  push:
    branches:
      - "**"
      - "!no-tests/**"
    tags:
      - "!**"
  pull_request:
    branches:
      - "**"
      - "!no-tests/**"
jobs:
  check-modules:
    name: Check Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Check whether or not necessary modules are installed.
        run: ./utils/check-necessary-modules
      - name: Check whether or not unnecessary modules are installed.
        run: ./utils/check-unnecessary-modules
  check-traspilation:
    name: Check whether or not transpilation is completed.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - name: Check transpilation
        run: |
          npm install
          npm run build
          git diff --exit-code -- ./lib
