name: Check commits
"on":
  push:
    branches:
      - "**"
      - "!no-tests/**"
    tags:
      - "!**"
  pull_request:
    branches:
      - "**"
      - "!no-tests/**"
jobs:
  check-modules:
    name: Check Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Check whether or not necessary modules are installed.
        run: ./utils/check-necessary-modules
      - name: Check whether or not unnecessary modules are installed.
        run: ./utils/check-unnecessary-modules
  lint-scripts-and-check-traspilation:
    name: Lint scripts and check whether or not transpilation is completed.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Install modules
        run: npm install
      - name: Lint scripts
        run: npm run lint
      - name: Check transpilation
        run: |
          npm run build
          git diff --exit-code -- ./lib
