name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
    tags:
      - '!*'
  pull_request:
    branches:
      - '*'
      - '*/*'
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        swift-version: ['5.1', 'DEVELOPMENT-SNAPSHOT-2019-09-30-a']
    runs-on: ${{ matrix.os }}
    name: Test of Action-setup-swift
    steps:
    - name: Install Swift.
      uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: View Swift Version
      run: swift --version
    - uses: actions/checkout@master
    - name: Run Swift
      run: cd swift-package-for-test && swift test
